/* Configs for each planet.

class_name: CSS class.
id: Planet identifier.
model_rotation_speed: Time in seconds for one full rotation of the model.
model_size: Base size for model in pixels.
name: Display name for h2.
orbit: Orbit parameters if not static.
panel_rotation_speed: Time in seconds for one full rotation in the panel.
panel_scale: Multiplier for the size in the panel.
panel_sprite_frame_height: Optional frame height in pixels for the panel spritesheet.
panel_sprite_frame_width: Optional frame width in pixels for the panel spritesheet.
panel_sprite_image: Optional secondary spritesheet asset for the info panel.
panel_sprite_rotation: Optional panel rotation, e.g. "90deg".
sprite_frame_height: Frame height in pixels for the model.
sprite_frame_width: Frame width in pixels for the model.
sprite_image: Spritesheet asset PNG.
sprite_rotation_direction: "clockwise" or "counterclockwise" for sprite animation direction.
sprite_flip_horizontal: Optional boolean to flip sprite horizontally.
sprite_flip_vertical: Optional boolean to flip sprite vertically.
z_index: Z-index stacking order in the model.
*/

window.solar_system_objects = [
    {
        id: "sun",
        name: "Sun",
        class_name: "solar_system_object--spritesheet solar_system_object--sun",
        model_size: 96,
        orbit: { around: "sun", radius_x: 0, radius_y: 0, period_seconds: 1 },
        panel_scale: 8,
        panel_rotation_speed: 0.8,
        sprite_frame_height: 32,
        sprite_frame_width: 32,
        sprite_image: "../Assets/Spr_Sun.png",
        sprite_rotation_direction: "counterclockwise",
        z_index: 19,
    },
    {
        id: "mercury",
        name: "Mercury",
        class_name: "solar_system_object--spritesheet solar_system_object--mercury",
        model_size: 12,
        orbit: { around: "sun", radius_x: 63, radius_y: 63, period_seconds: 4.8, phase_seconds: -1.2 },
        panel_scale: 8,
        panel_rotation_speed: 0.8,
        sprite_frame_height: 32,
        sprite_frame_width: 32,
        sprite_image: "../Assets/Spr_Mercury.png",
        sprite_rotation_direction: "counterclockwise",
        z_index: 17,
    },
    {
        id: "venus",
        name: "Venus",
        class_name: "solar_system_object--spritesheet solar_system_object--venus",
        model_size: 30,
        orbit: { around: "sun", radius_x: 73, radius_y: 73, period_seconds: 12.3, phase_seconds: -3.075 },
        panel_rotation_speed: 0.8,
        panel_scale: 8,
        sprite_flip_horizontal: true,
        sprite_frame_height: 32,
        sprite_frame_width: 32,
        sprite_image: "../Assets/Spr_Venus.png",
        sprite_rotation_direction: "counterclockwise",
        z_index: 15,
    },
    {
        id: "earth",
        name: "Earth",
        class_name: "solar_system_object--spritesheet solar_system_object--earth",
        model_rotation_speed: 6.4,
        model_size: 32,
        orbit: { around: "sun", radius_x: 83, radius_y: 83, period_seconds: 20, phase_seconds: -5 },
        panel_rotation_speed: 0.5,
        panel_scale: 8,
        sprite_frame_height: 32,
        sprite_frame_width: 32,
        sprite_image: "../Assets/Spr_Earth.png",
        sprite_rotation_direction: "counterclockwise",
        z_index: 11,
    },
    {
        id: "moon",
        name: "Moon",
        class_name: "solar_system_object--spritesheet solar_system_object--moon",
        model_size: 8,
        orbit: { around: "earth", radius_x: 18, radius_y: 18, period_seconds: 2.0, phase_seconds: -0.5 },
        panel_scale: 8,
        panel_rotation_speed: 0.8,
        sprite_flip_horizontal: true,
        sprite_frame_height: 32,
        sprite_frame_width: 32,
        sprite_image: "../Assets/Spr_Moon.png",
        sprite_rotation_direction: "counterclockwise",
        z_index: 13,
    },
    {
        id: "mars",
        name: "Mars",
        class_name: "solar_system_object--spritesheet solar_system_object--mars",
        model_rotation_speed: 24.6,
        model_size: 17,
        orbit: { around: "sun", radius_x: 99, radius_y: 99, period_seconds: 37.6, phase_seconds: -9.4 },
        panel_rotation_speed: 0.8,
        panel_scale: 8,
        sprite_flip_horizontal: true,
        sprite_flip_vertical: true,
        sprite_frame_height: 32,
        sprite_frame_width: 32,
        sprite_image: "../Assets/Spr_Mars.png",
        sprite_rotation_direction: "clockwise",
        z_index: 9,
    },
    {
        id: "jupiter",
        name: "Jupiter",
        class_name: "solar_system_object--spritesheet solar_system_object--jupiter",
        model_size: 96,
        orbit: { around: "sun", radius_x: 138, radius_y: 138, period_seconds: 237.2, phase_seconds: -59.3 },
        panel_scale: 8,
        panel_rotation_speed: 0.8,
        sprite_frame_height: 32,
        sprite_frame_width: 32,
        sprite_image: "../Assets/Spr_Jupiter.png",
        sprite_rotation_direction: "counterclockwise",
        z_index: 7,
    },
    {
        id: "saturn",
        name: "Saturn",
        class_name: "solar_system_object--spritesheet solar_system_object--saturn",
        model_rotation_speed: 73.65,
        model_size: 82,
        orbit: { around: "sun", radius_x: 206, radius_y: 206, period_seconds: 589.2, phase_seconds: -147.3 },
        panel_rotation_speed: 0.8,
        panel_scale: 8,
        sprite_frame_height: 64,
        sprite_frame_width: 64,
        sprite_image: "../Assets/Spr_Saturn.png",
        sprite_rotation_direction: "counterclockwise",
        z_index: 5,
    },
    {
        id: "uranus",
        name: "Uranus",
        class_name: "solar_system_object--spritesheet solar_system_object--uranus",
        model_rotation_speed: 10,
        model_size: 58,
        orbit: { around: "sun", radius_x: 281, radius_y: 281, period_seconds: 1680.2, phase_seconds: -420.05 },
        panel_rotation_speed: 0.8,
        panel_scale: 8,
        panel_sprite_rotation: "90deg",
        sprite_frame_height: 64,
        sprite_frame_width: 64,
        sprite_image: "../Assets/Spr_Uranus.png",
        sprite_rotation_direction: "clockwise",
        z_index: 3,
    },
    {
        id: "neptune",
        name: "Neptune",
        class_name: "solar_system_object--spritesheet solar_system_object--neptune",
        model_rotation_speed: 1,
        model_size: 56,
        orbit: { around: "sun", radius_x: 366, radius_y: 366, period_seconds: 3296, phase_seconds: -824 },
        panel_rotation_speed: 0.8,
        panel_scale: 8,
        sprite_frame_height: 32,
        sprite_frame_width: 32,
        sprite_image: "../Assets/Spr_Neptune.png",
        sprite_rotation_direction: "counterclockwise",
        z_index: 1,
    },
    {
        id: "pluto",
        name: "Pluto",
        class_name: "solar_system_object--spritesheet solar_system_object--pluto",
        model_size: 11,
        orbit: { around: "sun", radius_x: 481, radius_y: 466, period_seconds: 5900, phase_seconds: -1475 },
        panel_scale: 8,
        panel_rotation_speed: 0.8,
        sprite_frame_height: 32,
        sprite_frame_width: 32,
        sprite_image: "../Assets/Spr_Pluto.png",
        sprite_rotation_direction: "counterclockwise",
        z_index: 0,
    },
    {
        id: "eris",
        name: "Eris",
        class_name: "solar_system_object--spritesheet solar_system_object--eris",
        model_rotation_speed: 6.4,
        model_size: 14,
        orbit: { around: "sun", radius_x: 824, radius_y: 741, period_seconds: 20300, phase_seconds: -5075 },
        panel_rotation_speed: 0.5,
        panel_scale: 8,
        sprite_flip_vertical: true,
        sprite_frame_height: 32,
        sprite_frame_width: 32,
        sprite_image: "../Assets/Spr_Eris.png",
        sprite_rotation_direction: "counterclockwise",
        z_index: 21,
    }
];
