# Config
# ========================================================================================

# Uncomment and set the URL of your site (with protocol, e.g. `https://`)
# NOTE: You don't need to provide this property when hosting on GitHub Pages or Netlify.
# url:                   https://username.github.io

# Uncomment and set the "base URL" of your site.
# When your site is in a subdirectory, set to `/<name of directory>`,
# with a leading `/` but no trailing `/`. Use the empty string '' otherwise.
# NOTE: You don't need to provide this property when hosting on GitHub Pages or Netlify.
# baseurl:               '/hydejack-starter-kit'


# General settings
# ---------------------------------------------------------------------------------------

# Language of your content in 2-letter code, e.g.: en, de.
# You may also provide a location, e.g.: en-us, de_AT.
lang:                  en

# The title of your blog. Used in the sidebar and the browser tab.
title:                 Darragh McConville

# A short description (~150 chars) of the page used for the meta description tag.
# Can use markdown, but no more than one paragraph (enforced by `>`)
description:           >
  I build low level programs for game engines and other interactive experiences.
  Portfolio tracks all programming and artistic projects.

# A shorter description for the sidebar.
tagline:               Computer science and game development student.

# A list of keywords for your blog
keywords:              []

# A (square) logo for your site.
# If provided, it will be shown at the top of the sidebar.
# It also used by the `jekyll-seo-tag` plugin.
logo:                  /assets/img/logo.png

# This should be the same author as first entry in `_data/authors.yml`.
author:
  # Used by `jekyll-feed`:
  name:                <Darragh> <McConville>
  email:               <3Darragh@gmail.com>
  # # Used by `jekyll-seo-tag`:
  # twitter:             <username>

# Add links to the sidebar.
menu:
  - title:             Projects
    url:               /works/
  - title:             Resume
    url:               /resume/
  - title:             About
    url:               /about/

# This text will appear in a `<small>` tag in the footer of every page.
copyright:             © 2026. All rights reserved.

# Format of the permalinks
permalink:             /:categories/:year-:month-:day-:title/

# Pagination configuration (used by the `blog` layout)
paginate:              10
paginate_path:         /:num/


# Theme
# ---------------------------------------------------------------------------------------

theme: jekyll-theme-hydejack

# Customizaton
# ----------------------------------------------------------------------------------------

# Sidebar image and theme color of the site.
accent_image:
  background: url(https://raw.githubusercontent.com/3Darragh/Portfolio/main/projects/Portfolio_Subway_2.png) center/cover no-repeat
  overlay: true
accent_color:          rgb(159, 224, 153)

theme_color:           rgb(25,55,71)

defaults:
  - scope:
      path:            hyde/
    values:
      accent_color:    rgb(38,139,210)
      theme_color:     rgb(32,32,32)
      accent_image:
        background:    rgb(32,32,32)
        overlay:       true

  - scope:
      path:            assets/
    values:
      sitemap:         false

  - scope:
      path:            licenses/
    values:
      layout:          plain
      sitemap:         false

  - scope:
      type:            projects
    values:
      seo:
        type:          WebPage
  - scope:
      type:            featured_categories
    values:
      seo:
        type:          WebPage
  - scope:
      type:            featured_tags
    values:
      seo:
        type:          WebPage

kramdown:
  math_engine:         katex
  math_engine_opts:    {}
  footnote_backlink:   '&#x21a9;&#xfe0e;'


# Hydejack Settings
# ----------------------------------------------------------------------------------------

hydejack:
  post_addons:         [about, newsletter, related, random, comments]
  project_addons:      [about, newsletter, other, comments]
  no_mark_external:    false
  no_push_state:       false
  no_drawer:           false
  no_navbar:           false
  no_search:           false
  no_inline_css:       false
  no_page_style:       false
  no_break_layout:     false
  no_toc:              false
  no_third_column:     true
  no_large_headings:   false
  no_structured_data:  false
  no_theme_color:      false
  no_breadcrumbs:      false
  use_lsi:             true
  cookies_banner:      false
  advertise:           false
  hide_dates:          false
  hide_last_modified:  false
  dark_mode:
    always:            false
    dynamic:           true
    icon:              true
  offline:
    enabled:           false
    cache_version:     13
    precache_assets:
      - /assets/img/swipe.svg


# Collections
# ----------------------------------------------------------------------------------------

collections:
  featured_categories:
    permalink:         /:name/
    output:            true

  featured_tags:
    permalink:         /tag-:name/
    output:            true

  projects:
    permalink:         /projects/:path/
    output:            true


# File inclusion/exclusion
# ----------------------------------------------------------------------------------------

exclude:
  - .jekyll-cache
  - .sass-cache
  - .ruby-lsp
  - .wrangler
  - '*.toml'
  - vendor
  - Gemfile
  - Gemfile.lock
  - functions

include:
  - _routes.json
  - .well-known
  - LICENSE.md
  - projects/Portfolio_AC_1.png
  - projects/Portfolio_AC_2.png
  - projects/Portfolio_Locker_1.png
  - projects/Portfolio_Locker_2.png
  - projects/Portfolio_PC_1.png
  - projects/Portfolio_PC_2.png
  - projects/Portfolio_Resume.pdf
  - projects/Portfolio_Resume.png
  - projects/Portfolio_Subway_1.png
  - projects/Portfolio_Subway_2.png


# Plugins
# ----------------------------------------------------------------------------------------

plugins:
  - jekyll-default-layout
  - jekyll-feed
  - jekyll-optional-front-matter
  - jekyll-paginate
  - jekyll-readme-index
  - jekyll-redirect-from
  - jekyll-relative-links
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-titles-from-headings
  - jekyll-include-cache
  - jekyll-last-modified-at


# Plugin Configs
# ---------------------------------------------------------------------------------------

optional_front_matter:
  remove_originals:    true

readme_index:
  remove_originals:    true
  with_frontmatter:    true

relative_links:
  collections:         true

titles_from_headings:
  strip_title:         true
  collections:         true

compress_html:
  comments:            ["<!--", "-->"]
  clippings:           all
  endings:             all
  ignore:
    envs:              [development]

sass:
  style:               compressed

# Jekyll Compose Defaults
# ---------------------------------------------------------------------------------------

jekyll_compose:
  default_front_matter:
    drafts:
      layout: post
      description: >
        A short ~160 character description of your post for search engines,
        social media previews, etc.
      image:
        path: /assets/img/sidebar-bg.jpg
    posts:
      layout: post
      description: >
        A short ~160 character description of your post for search engines,
        social media previews, etc.
      image:
        path: /assets/img/sidebar-bg.jpg
    projects:
      layout: project
      description: >
        A short ~160 character description of your post for search engines,
        social media previews, etc.
      image:
        path: /assets/img/sidebar-bg.jpg
      links:
        - title: Project Link
          url: https://example.com

# Project folder direct includes.
# ----------------------------------------------------------------------------------------

projects_collection: projects